"""add missing job_runs columns

Revision ID: 1c77ba7ef964
Revises: 003
Create Date: 2026-01-21 19:30:46.746635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c77ba7ef964'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_cooccurrence', 'format',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('card_cooccurrence', 'cooccurrence_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_card_cooccurrence_card1'), table_name='card_cooccurrence')
    op.drop_index(op.f('ix_card_cooccurrence_card2'), table_name='card_cooccurrence')
    op.drop_index(op.f('ix_card_cooccurrence_card_a'), table_name='card_cooccurrence')
    op.drop_constraint(op.f('uq_card_cooccurrence'), 'card_cooccurrence', type_='unique')
    op.create_index('idx_cooccurrence_card', 'card_cooccurrence', ['card_a', 'format'], unique=False)
    op.create_index('idx_cooccurrence_pair', 'card_cooccurrence', ['card1_id', 'card2_id', 'format'], unique=False)
    op.create_unique_constraint('uq_cooccurrence_pair', 'card_cooccurrence', ['card1_id', 'card2_id', 'format'])
    op.drop_constraint(op.f('card_cooccurrence_card2_id_fkey'), 'card_cooccurrence', type_='foreignkey')
    op.drop_constraint(op.f('card_cooccurrence_card1_id_fkey'), 'card_cooccurrence', type_='foreignkey')
    op.drop_column('card_cooccurrence', 'updated_at')
    op.alter_column('cards', 'scryfall_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('cards', 'keywords',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               type_=postgresql.ARRAY(sa.String(length=100)),
               existing_nullable=True)
    op.alter_column('cards', 'image_uri',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('cards', 'image_uri_small',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('cards', 'image_uri_art_crop',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('cards', 'scryfall_uri',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('cards', 'oracle_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('cards', 'set_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cards_oracle_id'), table_name='cards')
    op.create_index('idx_cards_cmc', 'cards', ['cmc'], unique=False)
    op.create_index('idx_cards_colors', 'cards', ['colors'], unique=False, postgresql_using='gin')
    op.create_index('idx_cards_standard_legal', 'cards', ['is_standard_legal'], unique=False)
    op.create_index('idx_cards_type_line', 'cards', ['type_line'], unique=False)
    op.alter_column('conversations', 'summary',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('conversations', 'messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('decklists', sa.Column('finish_position', sa.String(length=50), nullable=True))
    op.add_column('decklists', sa.Column('archetype_tags', postgresql.ARRAY(sa.String(length=50)), nullable=True))
    op.alter_column('decklists', 'mtgtop8_deck_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('decklists', 'main_deck',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('decklists', 'sideboard',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('decklists', 'source_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('decklists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_decklists_mtgtop8_deck_id'), table_name='decklists')
    op.create_index(op.f('ix_decklists_mtgtop8_deck_id'), 'decklists', ['mtgtop8_deck_id'], unique=False)
    op.create_index(op.f('ix_decklists_archetype'), 'decklists', ['archetype'], unique=False)
    op.alter_column('decks', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('decks', 'main_deck',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('decks', 'sideboard',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('decks', 'share_token',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('decks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('decks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_deck_visibility', 'decks', ['visibility'], unique=False)
    op.create_unique_constraint('uq_deck_owner_name', 'decks', ['owner_id', 'name'])
    op.drop_constraint(op.f('decks_owner_id_fkey'), 'decks', type_='foreignkey')
    op.create_foreign_key(None, 'decks', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('events', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('events', sa.Column('source_id', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('event_name', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('event_date', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('num_players', sa.Integer(), nullable=True))
    op.alter_column('events', 'mtgtop8_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('events', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('events', 'format',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('events', 'source_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_events_mtgtop8_id'), table_name='events')
    op.create_index(op.f('ix_events_mtgtop8_id'), 'events', ['mtgtop8_id'], unique=False)
    op.create_index('idx_events_format_date', 'events', ['format', 'date'], unique=False)
    op.create_unique_constraint('uq_event_source', 'events', ['source', 'source_id'])
    op.drop_column('events', 'player_count')
    op.add_column('job_runs', sa.Column('records_deleted', sa.Integer(), nullable=True))
    op.alter_column('job_runs', 'run_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('job_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('job_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('job_runs', 'ended_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('job_runs', 'next_retry_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('job_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_job_runs_job_name_created'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_run_id'), table_name='job_runs')
    op.create_index(op.f('ix_job_runs_run_id'), 'job_runs', ['run_id'], unique=False)
    op.create_index('idx_job_runs_created', 'job_runs', ['created_at'], unique=False)
    op.create_index('idx_job_runs_name_status', 'job_runs', ['job_name', 'status'], unique=False)
    op.create_index(op.f('ix_job_runs_job_name'), 'job_runs', ['job_name'], unique=False)
    op.drop_column('job_runs', 'result_summary')
    op.alter_column('meta_snapshots', 'avg_finish',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('meta_snapshots', 'key_cards',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               type_=postgresql.ARRAY(sa.String(length=255)),
               existing_nullable=True)
    op.alter_column('meta_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_meta_snapshots_format_archetype'), table_name='meta_snapshots')
    op.create_index('idx_meta_format_date', 'meta_snapshots', ['format', 'snapshot_date'], unique=False)
    op.create_unique_constraint('uq_meta_snapshot', 'meta_snapshots', ['format', 'snapshot_date', 'archetype'])
    op.alter_column('preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reset_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('verification_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('verification_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_tokens', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('verification_tokens', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('reset_tokens', 'used_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('reset_tokens', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reset_tokens', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('preferences', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('preferences', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_meta_snapshot', 'meta_snapshots', type_='unique')
    op.drop_index('idx_meta_format_date', table_name='meta_snapshots')
    op.create_index(op.f('ix_meta_snapshots_format_archetype'), 'meta_snapshots', ['format', 'archetype'], unique=False)
    op.alter_column('meta_snapshots', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meta_snapshots', 'key_cards',
               existing_type=postgresql.ARRAY(sa.String(length=255)),
               type_=postgresql.ARRAY(sa.VARCHAR(length=100)),
               existing_nullable=True)
    op.alter_column('meta_snapshots', 'avg_finish',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.add_column('job_runs', sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_job_runs_job_name'), table_name='job_runs')
    op.drop_index('idx_job_runs_name_status', table_name='job_runs')
    op.drop_index('idx_job_runs_created', table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_run_id'), table_name='job_runs')
    op.create_index(op.f('ix_job_runs_run_id'), 'job_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_job_runs_job_name_created'), 'job_runs', ['job_name', 'created_at'], unique=False)
    op.alter_column('job_runs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_runs', 'next_retry_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('job_runs', 'ended_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('job_runs', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('job_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('job_runs', 'run_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('job_runs', 'records_deleted')
    op.add_column('events', sa.Column('player_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_event_source', 'events', type_='unique')
    op.drop_index('idx_events_format_date', table_name='events')
    op.drop_index(op.f('ix_events_mtgtop8_id'), table_name='events')
    op.create_index(op.f('ix_events_mtgtop8_id'), 'events', ['mtgtop8_id'], unique=True)
    op.alter_column('events', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'source_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('events', 'format',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('events', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('events', 'mtgtop8_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('events', 'num_players')
    op.drop_column('events', 'event_date')
    op.drop_column('events', 'event_name')
    op.drop_column('events', 'source_id')
    op.drop_column('events', 'source')
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.create_foreign_key(op.f('decks_owner_id_fkey'), 'decks', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_deck_owner_name', 'decks', type_='unique')
    op.drop_index('idx_deck_visibility', table_name='decks')
    op.alter_column('decks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('decks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('decks', 'share_token',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('decks', 'sideboard',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('decks', 'main_deck',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('decks', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_decklists_archetype'), table_name='decklists')
    op.drop_index(op.f('ix_decklists_mtgtop8_deck_id'), table_name='decklists')
    op.create_index(op.f('ix_decklists_mtgtop8_deck_id'), 'decklists', ['mtgtop8_deck_id'], unique=True)
    op.alter_column('decklists', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('decklists', 'source_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('decklists', 'sideboard',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('decklists', 'main_deck',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('decklists', 'mtgtop8_deck_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('decklists', 'archetype_tags')
    op.drop_column('decklists', 'finish_position')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('conversations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('conversations', 'summary',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_index('idx_cards_type_line', table_name='cards')
    op.drop_index('idx_cards_standard_legal', table_name='cards')
    op.drop_index('idx_cards_colors', table_name='cards', postgresql_using='gin')
    op.drop_index('idx_cards_cmc', table_name='cards')
    op.create_index(op.f('ix_cards_oracle_id'), 'cards', ['oracle_id'], unique=False)
    op.alter_column('cards', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cards', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cards', 'set_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('cards', 'oracle_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('cards', 'scryfall_uri',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('cards', 'image_uri_art_crop',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('cards', 'image_uri_small',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('cards', 'image_uri',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('cards', 'keywords',
               existing_type=postgresql.ARRAY(sa.String(length=100)),
               type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
               existing_nullable=True)
    op.alter_column('cards', 'scryfall_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('card_cooccurrence', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('card_cooccurrence_card1_id_fkey'), 'card_cooccurrence', 'cards', ['card1_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('card_cooccurrence_card2_id_fkey'), 'card_cooccurrence', 'cards', ['card2_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_cooccurrence_pair', 'card_cooccurrence', type_='unique')
    op.drop_index('idx_cooccurrence_pair', table_name='card_cooccurrence')
    op.drop_index('idx_cooccurrence_card', table_name='card_cooccurrence')
    op.create_unique_constraint(op.f('uq_card_cooccurrence'), 'card_cooccurrence', ['card1_id', 'card2_id', 'format'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_card_cooccurrence_card_a'), 'card_cooccurrence', ['card_a', 'format'], unique=False)
    op.create_index(op.f('ix_card_cooccurrence_card2'), 'card_cooccurrence', ['card2_id'], unique=False)
    op.create_index(op.f('ix_card_cooccurrence_card1'), 'card_cooccurrence', ['card1_id'], unique=False)
    op.alter_column('card_cooccurrence', 'cooccurrence_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('card_cooccurrence', 'format',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
