"""change cmc to float

Revision ID: f243f38bb0ca
Revises: 1c77ba7ef964
Create Date: 2026-01-21 19:34:39.240431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f243f38bb0ca'
down_revision: Union[str, None] = '1c77ba7ef964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'cmc',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'cmc',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=4, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
